const $=s=>document.querySelector(s);const fmt=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').trim();
const seedCards=[
{id:1,bank:'KBank',name:'Cashback Platinum',foreignFeeRate:.03,lastSynced:'Sep 30, 2026',rules:[{category:'Dining',mcc:['5812','5814'],rate:.08,cap:500000,used:170000},{category:'Grocery',mcc:['5411'],rate:.05,cap:300000,used:80000},{category:'Other',mcc:['*'],rate:.01,cap:200000,used:45000}]},
{id:2,bank:'UOB',name:'One Card',foreignFeeRate:.025,lastSynced:'Sep 30, 2026',rules:[{category:'Online',mcc:['*'],rate:.06,cap:600000,used:420000},{category:'Dining',mcc:['5812','5814'],rate:.04,cap:300000,used:0},{category:'Other',mcc:['*'],rate:.005,cap:150000,used:20000}]},
{id:3,bank:'HSBC',name:'Live+',foreignFeeRate:.0275,lastSynced:'Sep 30, 2026',rules:[{category:'Dining',mcc:['5812','5814'],rate:.06,cap:400000,used:90000},{category:'Shopping',mcc:['5311','5691'],rate:.04,cap:250000,used:250000},{category:'Other',mcc:['*'],rate:.005,cap:150000,used:0}]}
];
const merchants=[{aliases:['hlc','highlands','cà phê highlands','ca phe highlands'],name:'Highlands Coffee',mcc:'5814',category:'Dining',distance:'120 m'},{aliases:['wm','winmart','vinmart','siêu thị winmart'],name:'WinMart',mcc:'5411',category:'Grocery',distance:'300 m'},{aliases:['tgdd','thế giới di động','the gioi di dong'],name:'Thế Giới Di Động',mcc:'5732',category:'Electronics',distance:'800 m'},{aliases:['sp','shopee','sốp pi'],name:'Shopee',mcc:'5311',category:'Shopping',distance:'Online'}];
let state=JSON.parse(localStorage.getItem('cardCashbackState')||'null')||{tab:'home',cards:seedCards,history:[],merchant:merchants[0],merchantText:'HLC',amount:'500',currency:'VND',customCurrency:'',channel:'In-store',selectedCardId:1,showSuggestions:false};
function save(){localStorage.setItem('cardCashbackState',JSON.stringify(state))}function amountBase(){return(Number(state.amount)||0)*(state.currency==='VND'?1000:1)}function isForeign(){return state.currency!=='VND'}
function recs(){return state.cards.map(card=>{const exact=card.rules.find(r=>r.mcc.includes(state.merchant.mcc));const online=state.channel==='Online'?card.rules.find(r=>r.category==='Online'):null;const fallback=card.rules.find(r=>r.category==='Other')||card.rules[0];const rule=online&&(!exact||online.rate>exact.rate)?online:(exact||fallback);const cashback=Math.min(amountBase()*rule.rate,Math.max(0,rule.cap-rule.used));const fee=isForeign()?amountBase()*card.foreignFeeRate:0;return{card,rule,cashback,fee,net:cashback-fee}}).sort((a,b)=>b.net-a.net)}
function render(){const rs=recs();if(!rs.some(x=>x.card.id===state.selectedCardId))state.selectedCardId=rs[0]?.card.id;app.innerHTML=`<div class="phone"><header class="header"><div class="eyebrow">SMART WALLET</div><h1>Card Cashback</h1></header><div class="content">${state.tab==='home'?home(rs):state.tab==='cards'?cardsPage():historyPage()}</div>${nav()}</div>`;bind();save()}
function home(rs){let q=norm(state.merchantText);let sug=state.showSuggestions&&q?merchants.filter(m=>norm(m.name).includes(q)||m.aliases.some(a=>norm(a).includes(q)||q.includes(norm(a)))):[];return `<div class="relative"><label class="label">MERCHANT</label><div class="search"><span>▣</span><input id="merchantInput" value="${state.merchantText}" placeholder="HLC, Thế Giới Di Động"><button id="searchBtn">⌕</button></div>${sug.length?`<div class="suggestions">${sug.map((m,i)=>`<button data-merchant="${merchants.indexOf(m)}"><span><b>${m.name}</b><small>${m.category} · MCC ${m.mcc}</small></span><small>${m.distance}</small></button>`).join('')}</div>`:''}</div><div class="merchant"><b>${state.merchant.name}</b><span class="muted">${state.merchant.category} · MCC ${state.merchant.mcc}</span></div><div class="grid"><div><label class="label">AMOUNT</label><input id="amount" class="field" inputmode="decimal" value="${state.amount}"><div class="hint">${state.currency==='VND'?'Unit: thousand VND':'Foreign fees included in ranking'}</div></div><div><label class="label">CURRENCY</label><select id="currency" class="field"><option ${state.currency==='VND'?'selected':''}>VND</option><option ${state.currency==='USD'?'selected':''}>USD</option><option ${state.currency==='Other'?'selected':''}>Other</option></select></div></div>${state.currency==='Other'?`<input id="customCurrency" class="field" maxlength="3" value="${state.customCurrency}" placeholder="THB">`:''}<div class="segment"><button data-channel="In-store" class="${state.channel==='In-store'?'active':''}">⌖ In-store</button><button data-channel="Online" class="${state.channel==='Online'?'active':''}">⌁ Online</button></div><div class="section-title"><b>Recommended cards</b><small>Ranked by net benefit</small></div>${rs.map((r,i)=>recCard(r,i)).join('')}<button id="record" class="primary">Record Transaction</button>`}
function recCard(r,i){const selected=state.selectedCardId===r.card.id;const value=state.currency==='VND'?r.cashback/1000:r.net;return `<button class="rec ${selected?'selected':''}" data-card="${r.card.id}"><span class="rank">${selected?'✓':i+1}</span><span><b>${i===0?'Best choice':'Priority '+(i+1)} · ${r.card.name}</b><small>${(r.rule.rate*100).toFixed(1)}% cashback · ${r.rule.category}</small>${isForeign()?`<small class="breakdown">Cashback ${fmt(r.cashback)} − fee ${fmt(r.fee)}</small>`:''}</span><span class="value ${r.net<0?'negative':''}">${fmt(value)}<small>${state.currency==='VND'?'K VND cashback':'net '+(state.currency==='Other'?(state.customCurrency||'FX'):state.currency)}</small></span></button>`}
function cardsPage(){return `<div class="between"><div><h2>My cards</h2><span class="muted">Issuer rules and foreign fees</span></div><button id="sync" class="primary" style="width:48px;height:48px">↻</button></div><div class="sync">Monthly policy refresh is scheduled for the final day of each month. This mobile release uses validated sample data; a deployed backend is required for live issuer crawling.</div>${state.cards.map(c=>`<div class="card"><div class="between"><span><b>${c.bank} · ${c.name}</b><small>Last synced: ${c.lastSynced}</small></span><span style="text-align:right"><b style="color:#dc2626">${(c.foreignFeeRate*100).toFixed(2)}%</b><small>foreign fee</small></span></div>${c.rules.map(r=>`<div class="between" style="margin-top:10px;font-size:12px"><span>${r.category} · ${(r.rate*100).toFixed(1)}%</span><span class="muted">MCC ${r.mcc.join(', ')}</span></div>`).join('')}</div>`).join('')}`}
function historyPage(){return `<h2>History</h2>${state.history.length?state.history.map(t=>`<div class="card between"><span><b>${t.merchant}</b><small>${t.card}</small>${t.currency!=='VND'?`<small>Cashback ${fmt(t.cashback)} · Fee ${fmt(t.fee)} · Net ${fmt(t.net)}</small>`:''}</span><span style="text-align:right"><b>${fmt(t.amount)} ${t.currency}</b><button class="danger" data-delete="${t.id}">Delete</button></span></div>`).join(''):`<div class="empty">No transactions yet.</div>`}`}
function nav(){return `<nav class="nav">${[['home','⌂','Home'],['cards','▣','Cards'],['history','◷','History']].map(([id,ic,n])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}"><span style="font-size:20px">${ic}</span>${n}</button>`).join('')}</nav>`}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});if(state.tab==='home'){const mi=$('#merchantInput');mi.onfocus=()=>{state.showSuggestions=true;render()};mi.oninput=e=>{state.merchantText=e.target.value;state.showSuggestions=true;render()};document.querySelectorAll('[data-merchant]').forEach(b=>b.onclick=()=>{state.merchant=merchants[+b.dataset.merchant];state.merchantText=state.merchant.name;state.showSuggestions=false;render()});$('#amount').oninput=e=>{state.amount=e.target.value.replace(/[^0-9.]/g,'');render()};$('#currency').onchange=e=>{state.currency=e.target.value;render()};if($('#customCurrency'))$('#customCurrency').oninput=e=>{state.customCurrency=e.target.value.toUpperCase();save()};document.querySelectorAll('[data-channel]').forEach(b=>b.onclick=()=>{state.channel=b.dataset.channel;render()});document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{state.selectedCardId=+b.dataset.card;render()});$('#record').onclick=record}else if(state.tab==='cards'){$('#sync').onclick=()=>{state.cards=state.cards.map(c=>({...c,lastSynced:new Date().toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}));render()}}else{document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeTx(+b.dataset.delete))}}
function record(){const r=recs().find(x=>x.card.id===state.selectedCardId)||recs()[0];if(!r||!amountBase())return;state.cards=state.cards.map(c=>c.id!==r.card.id?c:{...c,rules:c.rules.map(x=>x.category===r.rule.category?{...x,used:x.used+r.cashback}:x)});state.history.unshift({id:Date.now(),merchant:state.merchant.name,card:r.card.name,ruleCategory:r.rule.category,amount:Number(state.amount),currency:state.currency==='Other'?(state.customCurrency||'Other'):state.currency,cashback:r.cashback,fee:r.fee,net:r.net});state.tab='history';render()}
function removeTx(id){const t=state.history.find(x=>x.id===id);if(!t)return;state.cards=state.cards.map(c=>c.name!==t.card?c:{...c,rules:c.rules.map(r=>r.category===t.ruleCategory?{...r,used:Math.max(0,r.used-t.cashback)}:r)});state.history=state.history.filter(x=>x.id!==id);render()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
